
import jaco.mp3.player.MP3Player;
import java.io.File;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class SingularPlural extends javax.swing.JFrame {
    static int score=0;
 
    public SingularPlural() {
        initComponents();
        jLabel11.setVisible(true);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jButton1.setVisible(true);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jButton10.setVisible(false);
        

    }
public static final String SONG="C:\\Users\\hp\\Desktop\\icons\\game\\Sound effect\\Correct-Answer-3-Sound-Effect_0ZQ-Lk--ILE.mp3";
MP3Player mp3player=new MP3Player(new File(SONG));
public static final String Song2="C:\\Users\\hp\\Desktop\\icons\\game\\Sound effect\\Game-Over-Sound-Effect-HD_NN_8vfN0HP4.mp3";
MP3Player mp3player2=new MP3Player(new File(Song2));
public static final String Song3="C:\\Users\\hp\\Desktop\\icons\\game\\Sound effect\\Buzzer-Wrong-Answer-Gaming-Sound-Effect-HD_FRpq7o1mKXY.mp3";
MP3Player mp3player3=new MP3Player(new File(Song3));
public static final String SONG4="C:\\Users\\hp\\Desktop\\icons\\game\\Sound effect\\Mouse-Click-Sound-Effect-HD_h6_8SlZZwvQ.mp3";
MP3Player mp3player4=new MP3Player(new File(SONG4));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfbg.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 270, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scr.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, 80));

        lblScore.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblScore.setForeground(new java.awt.Color(51, 255, 153));
        getContentPane().add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 140, 60));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 0));
        jLabel11.setText("Pencil");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 220, 70));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 255, 0));
        jLabel12.setText("Dog");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 220, 70));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 255, 0));
        jLabel13.setText("Bus");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 220, 70));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 255, 0));
        jLabel14.setText("Boy");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 220, 70));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 255, 0));
        jLabel15.setText("Box");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 220, 70));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 255, 0));
        jLabel16.setText("Mouse");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 220, 70));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 255, 0));
        jLabel17.setText("Spoon");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 220, 70));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 255, 0));
        jLabel18.setText("Body");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 220, 70));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 255, 0));
        jLabel19.setText("Toy");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 220, 70));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 255, 0));
        jLabel20.setText("Knife");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 220, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, 70));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, 70));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, 70));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, 70));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, 70));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, 70));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, 70));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, 70));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pf.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3D-Red-Heart-Image.png"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 50, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3D-Red-Heart-Image.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 50, 40));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3D-Red-Heart-Image.png"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 50, 40));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRE.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 50, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfbg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
       
       String plu=jTextField1.getText();
        if(plu.equals("Pencils")||plu.equals("pencils"))
           {
               mp3player.play();
            score=score+1;
            lblScore.setText(String.valueOf(score));
            jLabel11.setVisible(false);
            jLabel12.setVisible(true);
            jTextField1.setText("");
            jButton1.setVisible(false);
            jButton2.setVisible(true);
           }
           else
           {
               mp3player3.play();
               jLabel11.setVisible(false);
               lblScore.setText(String.valueOf(score));
               jLabel12.setVisible(true);
               jTextField1.setText("");
                jButton1.setVisible(false);
            jButton2.setVisible(true);
         
           }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String plu=jTextField1.getText();
        if(plu.equals("Dogs"))
           {
                mp3player.play();
            score=score+1;
            lblScore.setText(String.valueOf(score));
            jLabel12.setVisible(false);
            jLabel13.setVisible(true);
            jTextField1.setText("");
            jButton2.setVisible(false);
            jButton3.setVisible(true);
           }
           
           else
           {
               mp3player3.play();
               jLabel12.setVisible(false);
               lblScore.setText(String.valueOf(score));
               jLabel13.setVisible(true);
               jTextField1.setText("");
                jButton2.setVisible(false);
            jButton3.setVisible(true);
         
           }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String plu=jTextField1.getText();
        if(plu.equals("Buses"))
           {
                mp3player.play();
            score=score+1;
            lblScore.setText(String.valueOf(score));
            jLabel13.setVisible(false);
            jLabel14.setVisible(true);
            jTextField1.setText("");
            jButton3.setVisible(false);
            jButton4.setVisible(true);
           }
           else
           {
               mp3player3.play();
               jLabel13.setVisible(false);
               lblScore.setText(String.valueOf(score));
               jLabel14.setVisible(true);
               jTextField1.setText("");
               jButton3.setVisible(false);
               jButton4.setVisible(true);
         
           }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String plu=jTextField1.getText();
        if(plu.equals("Boys"))
           {
                mp3player.play();
            score=score+1;
            lblScore.setText(String.valueOf(score));
            jLabel14.setVisible(false);
            jLabel15.setVisible(true);
            jTextField1.setText("");
            jButton4.setVisible(false);
            jButton5.setVisible(true);
           }
           else
           {
               mp3player3.play();
               jLabel14.setVisible(false);
               lblScore.setText(String.valueOf(score));
               jLabel15.setVisible(true);
               jTextField1.setText("");
                jButton4.setVisible(false);
            jButton5.setVisible(true);
         
           }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String plu=jTextField1.getText();
        if(plu.equals("Boxes"))
           {
                mp3player.play();
            score=score+1;
            lblScore.setText(String.valueOf(score));
            jLabel15.setVisible(false);
            jLabel16.setVisible(true);
            jTextField1.setText("");
            jButton5.setVisible(false);
            jButton6.setVisible(true);
           }
           else
           {
               mp3player3.play();
               jLabel15.setVisible(false);
               lblScore.setText(String.valueOf(score));
               jLabel16.setVisible(true);
               jTextField1.setText("");
                jButton5.setVisible(false);
            jButton6.setVisible(true);
         
           }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String plu=jTextField1.getText();
        if(plu.equals("Mice"))
           {
                mp3player.play();
            score=score+1;
            lblScore.setText(String.valueOf(score));
            jLabel16.setVisible(false);
            jLabel17.setVisible(true);
            jTextField1.setText("");
            jButton6.setVisible(false);
            jButton7.setVisible(true);
           }
           else
           {
               mp3player3.play();
               jLabel16.setVisible(false);
               lblScore.setText(String.valueOf(score));
               jLabel17.setVisible(true);
               jTextField1.setText("");
                jButton6.setVisible(false);
            jButton7.setVisible(true);
         
           }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String plu=jTextField1.getText();
        if(plu.equals("Spoons"))
           {
                mp3player.play();
            score=score+1;
            lblScore.setText(String.valueOf(score));
            jLabel17.setVisible(false);
            jLabel18.setVisible(true);
            jTextField1.setText("");
            jButton7.setVisible(false);
            jButton8.setVisible(true);
           }
           else
           {
               mp3player3.play();
               jLabel17.setVisible(false);
               lblScore.setText(String.valueOf(score));
               jLabel18.setVisible(true);
               jTextField1.setText("");
                jButton7.setVisible(false);
            jButton8.setVisible(true);
         
           }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String plu=jTextField1.getText();
        if(plu.equals("Bodies"))
           {
            score=score+1;
             mp3player.play();
            lblScore.setText(String.valueOf(score));
            jLabel18.setVisible(false);
            jLabel19.setVisible(true);
            jTextField1.setText("");
            jButton8.setVisible(false);
            jButton9.setVisible(true);
           }
           else
           {
               mp3player3.play();
               jLabel18.setVisible(false);
               lblScore.setText(String.valueOf(score));
               jLabel19.setVisible(true);
               jTextField1.setText("");
                jButton8.setVisible(false);
            jButton9.setVisible(true);
         
           }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String plu=jTextField1.getText();
        if(plu.equals("Toys"))
           {
            score=score+1;
             mp3player.play();
            lblScore.setText(String.valueOf(score));
            jLabel19.setVisible(false);
            jLabel20.setVisible(true);
            jTextField1.setText("");
            jButton9.setVisible(false);
            jButton10.setVisible(true);
           }
           else
           {
               mp3player3.play();
               jLabel19.setVisible(false);
               lblScore.setText(String.valueOf(score));
               jLabel20.setVisible(true);
               jTextField1.setText("");
                jButton9.setVisible(false);
            jButton10.setVisible(true);
         
           }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String plu=jTextField1.getText();
        if(plu.equals("Knives"))
           {
               mp3player.play();
            score=score+1;
             mp3player.play();
            lblScore.setText(String.valueOf(score));
            JOptionPane.showMessageDialog(null, "Your Score is"+score);
           }
           else
           {
               mp3player3.play();
                JOptionPane.showMessageDialog(null, "Your Score is"+score);
           }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        mp3player4.play();
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to stop playing","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            new Math().setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingularPlural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingularPlural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingularPlural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingularPlural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingularPlural().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables
}
