/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import jaco.mp3.player.MP3Player;
import java.io.File;
import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }
public static final String SONG2="C:\\Users\\hp\\Desktop\\icons\\game\\Sound effect\\Mouse-Click-Sound-Effect-HD_h6_8SlZZwvQ.mp3";
MP3Player mp3player2=new MP3Player(new File(SONG2));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        check2 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0eu.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 230, 50));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 280, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0ep.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 220, 50));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 280, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0re.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 210, 40));

        pass2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass2ActionPerformed(evt);
            }
        });
        getContentPane().add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 280, 40));

        jButton1.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        jButton1.setText("Sign up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 190, 50));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1button_previous_01.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 70, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/su_1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -50, 720, 200));

        check.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        check.setForeground(new java.awt.Color(0, 255, 0));
        check.setText("Show Password");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        getContentPane().add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 130, 30));

        check2.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        check2.setForeground(new java.awt.Color(0, 255, 0));
        check2.setText("Show Password");
        check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check2ActionPerformed(evt);
            }
        });
        getContentPane().add(check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 130, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0ui.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 200, 40));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 280, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/201.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mp3player2.play();
            String a,b,c,d;
                    a=jTextField2.getText();
                    b=jPasswordField1.getText();
                    c=pass2.getText();
                   d=jTextField1.getText();
                    if(jTextField1.getText().trim().isEmpty() && jPasswordField1.getText().trim().isEmpty()&& jTextField2.getText().trim().isEmpty())
                    {
                        JOptionPane.showMessageDialog(null, "insuuficient Data");
                    }
                    else if(jTextField1.getText().trim().isEmpty()){
                      JOptionPane.showMessageDialog(null, "User name is empty");
                      
                    }
                    else if(jTextField2.getText().trim().isEmpty()){
                      JOptionPane.showMessageDialog(null, "User ID is empty");
                    }
                    else if(jPasswordField1.getText().trim().isEmpty()){
                        JOptionPane.showMessageDialog(null,"Empty Password");
                    }
                    else if(pass2.getText().trim().isEmpty()){
                        JOptionPane.showMessageDialog(null,"Please confirm your password");
                    }
                    else
                     if(b.length()>=6&&b.equals(c)){
                        try{       
              Class.forName("com.mysql.jdbc.Driver");
              Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3309/Game_1","root","Dipti077");
              Statement st = con.createStatement();
              st.executeUpdate("insert into Signup  values(' "+a+" ',' "+d+" ','"+b+"')");
             JOptionPane.showMessageDialog(null, "Signed up Successfully");
              setVisible(false);
              jTextField1.setText("");
              jPasswordField1.setText("");
              pass2.setText("");   
              jTextField1.setText("");
                            }
                                  catch(Exception e){
                                  JOptionPane.showMessageDialog(null, "jndfj,ndgjr");
                                  }
                        setVisible(false);
                     }
                        else {
                         JOptionPane.showMessageDialog(null, "Password didn't match ");
                         JOptionPane.showMessageDialog(null, "A password must be 6 character long ");     
                    }
                     if(b.length()<=6){
                         if(jPasswordField1.getText().trim().isEmpty()){                              
                            }
                            else{
                                  JOptionPane.showMessageDialog(null, "A password must be 6 character long ");  
                            }
                            
                    }
                    if(b.equals(c)){
                    } 
                    else{
                            if(pass2.getText().trim().isEmpty()){                              
                            }
                            else{
                                  JOptionPane.showMessageDialog(null, "Password didn't match");   
                            }
                        
                         
                    }
                     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        mp3player2.play();
         setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void pass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass2ActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
          mp3player2.play();
         if(check.isSelected()){
            jPasswordField1.setEchoChar((char)0);

        }
        else{
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_checkActionPerformed

    private void check2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check2ActionPerformed
        // TODO add your handling code here:
          mp3player2.play();
         if(check2.isSelected()){
           pass2.setEchoChar((char)0);

        }
        else{
            pass2.setEchoChar('*');
        }
    }//GEN-LAST:event_check2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check;
    private javax.swing.JCheckBox check2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPasswordField pass2;
    // End of variables declaration//GEN-END:variables
}
